### ISSUE TITLE
Table sms_routing not exist!

### ISSUE THREAD

**Issue by vsc55** [simontelephonics/smsconnector#1]
Hi,
First of all thanks with module.
I have installed it to test it and I have seen that when accessing it an error is produced since a reference is made to a table called "sms_routing" that is not created when installing the module.

Is it necessary to have any other module installed?

Greetings and thank you.

**Comment by billsimon** [comment]
It depends on the sms module. Please install that first.

I will fix the module manifest to require sms be installed.

**Comment by vsc55** [comment]
Hi @billsimon,
Yes, I have seen that it is required, but it would depend on it to install the module automatically.
Now I am going to publish a PR with that correction and some other i18n correction.
