### ISSUE TITLE
New Feature - Implement Ajax, multi user

### ISSUE THREAD

**Issue by vsc55** [simontelephonics/smsconnector#13]
Hi @billsimon,

I am implementing the option to create and edit numbers via ajax with a modal panel.
As soon as I have it, I create a PR for you to take a look at.

Here a capture:
![imagen](https://user-images.githubusercontent.com/13438676/230148260-d52d6564-f0bf-4842-9f3a-6aea3d25a681.png)
![imagen](https://user-images.githubusercontent.com/13438676/230148159-9424efb7-5ed1-4456-b6dc-3ee4507d1136.png)

**Comment by vsc55** [comment]
![imagen](https://user-images.githubusercontent.com/13438676/230886160-2ee74c80-eac8-483e-82da-585172827988.png)

**Comment by billsimon** [comment]
Fixed with tag v16.0.7beta
