### ISSUE TITLE
Bruteforce Prevention / Error Logs

### ISSUE THREAD

**Issue by pitzkey** [simontelephonics/smsconnector#16]
Hello,

Thank you for this awesome module. I see that the incoming webhooks are now going to a single provider.php script which makes things easier.

However, perhaps I missed it, I don't see anywhere that error get logged to.

And since we are talking about logging, I think it'll be great if we can add fail2ban integration to catch IPs of attackers

Thanks again

**Comment by billsimon** [comment]
Errors as well as api responses and webhooks are getting logged in /var/log/asterisk/freepbx.log

**Comment by billsimon** [comment]
Revisiting this ticket - fail2ban monitoring of web server seems to be out of scope of the module.
