### ISSUE TITLE
Install Issue: Module: "SMS Connector", File: "/var/www/html/admin/modules/smsconnector/assets/less/cache/lessphp_f02a0d2c08fb86d35bec7c2092ad9a27.list altered"

### ISSUE THREAD

**Issue by jaredirby** [simontelephonics/smsconnector#21]
Receiving this error message at the top of the dashboard in FreePBX. 

Module: "SMS Connector", File: "/var/www/html/admin/modules/smsconnector/assets/less/cache/lessphp_f02a0d2c08fb86d35bec7c2092ad9a27.list altered"

In module administration panel, I have this message for SMS Connector module:

Signature Status: | Module has been tampered. Please redownload (What Does this Mean?)

I am using FreePBX 16.0.40.4 and all modules/system up to date. I installed the module via the command line instructions.

Current PBX Version:16.0.40.4
Current System Version: 12.7.8-2306-1.sng7

**Comment by billsimon** [comment]
Looks like I made a mistake in the packaging of the module. Sorry! I'll put up a new release soon.

**Comment by billsimon** [comment]
Did you remember to fwconsole r (reload) after installing?

**Comment by billsimon** [comment]
Sorry, I'm not able to reproduce that problem.

Try:

`fwconsole ma delete smsconnector`
`fwconsole r`
`fwconsole ma downloadinstall https://github.com/simontelephonics/smsconnector/releases/download/v16.0.8/smsconnector-16.0.8.tar.gz`
`fwconsole r`
