### ISSUE TITLE
FlowRoute Setup and configuration

### ISSUE THREAD

**Issue by shuffman2006** [simontelephonics/smsconnector#24]
New to this but can someone please give a little better instructions on the installation and configuration for Flowroute, I was able to install on freebpx but not figuring the flowroute configuration, and in the FreePBX  under user managements, SMS Connector it says "Not yewt implemented. Go to SMS Connector, and I have the account configured in the SMS Connector.

**Comment by billsimon** [comment]
This question was addressed in a [FreePBX community forum post](https://community.freepbx.org/t/flowroute-and-freepbx-sms-setup/92360/12?u=billsimon).
