### ISSUE TITLE
Voxtelesys

### ISSUE THREAD

**Issue by wecaredoyou** [simontelephonics/smsconnector#26]
Using Voxtelesys
Server Error: Unable to send message: HTTP 422, {"status":"error","error":"to must be an array"}
number to entered in 11digit . key and messaging app and associated to phone number at Voxtelesys.
pasted webhook given in providers at smsconnector. also pasted key from voxtelesys into the setting under voxtelesys in smsconnector

Also no messages are getting into freepbx either, but voxtelesys shows message arrived in their log just not getting to freepbx no errors show on their end either direction.

**Comment by billsimon** [comment]
Voxtelesys code was contributed by @john08burke . Perhaps he can help with this issue.

**Comment by wecaredoyou** [comment]
I found the issue this morning and proposed a fix on Github.  Now able to send sms to voxtelesys without error  sms connector Server Error: Unable to send message: HTTP 422, {"status":"error","error":"to must be an array"}

**Comment by billsimon** [comment]
Thanks for the fix. I’ll get it added soon.

**Comment by john08burke** [comment]
Hi! Confirming that the "to" field needs to be wrapped as an array (sorry about that, missed that in the initial commit). Are you still having issues receiving inbound messages?

**Comment by wecaredoyou** [comment]
Yes outbound fine now but no inbound.. not sure if it’s my message context in the extensions_customs or if something amiss elsewhere. Out though working great Get daily inspirational quotes delivered straight to your inbox!Sign up now and receive a quote every day to brighten your mornings and inspire your day. Don't miss out on this wonderful opportunity!Click here to sign up for free!Sign Up Now    ---- On Sun, 05 Nov 2023 14:28:42 -0500  ***@***.******@***.***> wrote ----  
Hi! Confirming that the "to" field needs to be wrapped as an array (sorry about that, missed that in the initial commit). Are you still having issues receiving inbound messages?

**Comment by john08burke** [comment]
Hey @wecaredoyou, I have responded on the ticket that you opened w/ Voxtelesys support for the inbound issues as the problem looks likes it's outside the scope of this project.
