### ISSUE TITLE
Receive SMS

### ISSUE THREAD

**Issue by dperron25** [simontelephonics/smsconnector#31]
Hi i have configure with telnix i can send sms but cannot receive sms and in freepbx log i dont see anything

**Comment by dperron25** [comment]
all port in firewall is open

**Comment by dperron25** [comment]
in apache log i dont see any connection but all firewall on freepbx is off

**Comment by billsimon** [comment]
If you don't see the connection in the apache log then the webhook isn't getting to your server. So you will need to do some network troubleshooting; perhaps also verify you have a valid TLS certificate in place. This issue tracker is for module bugs and not suitable for troubleshooting and support. Paid support is available; contact us via https://simon.tel

**Comment by sdwru** [comment]
Have you tested this with softphones besides Sangoma?  I can't get inbound to work with Telnyx either but I am not using Sangoma softphones.  cerficates and API are definitely working because it gets to the server and UCP just fine, so I think this may be a bug.
