### ISSUE TITLE
Undefined array key "view", FreePBX 17

### ISSUE THREAD

**Issue by vsc55** [simontelephonics/smsconnector#39]
Hi @billsimon,

I am testing the Beta of FreePBX 17 and it seems that there is a problem with the module since this error appears when accessing.
The test is done on a clean Debian 12 and I have installed FreePBX 17 with the official script:
https://github.com/FreePBX/sng_freepbx_debian_install

Error:
```
Whoops\Exception\ErrorException thrown with message "Undefined array key "view""

Stacktrace:
#5 Whoops\Exception\ErrorException in /var/www/html/admin/modules/smsconnector/views/page.main.php:4
#4 Whoops\Run:handleError in /var/www/html/admin/modules/smsconnector/views/page.main.php:4
#3 include in /var/www/html/admin/libraries/view.functions.php:151
#2 load_view in /var/www/html/admin/modules/smsconnector/Smsconnector.class.php:750
#1 FreePBX\modules\Smsconnector:showPage in /var/www/html/admin/modules/smsconnector/page.smsconnector.php:2
#0 include in /var/www/html/admin/config.php:658

```

I review it and create a pr as soon as it is ready.

**Comment by vsc55** [comment]
I close the issue since I see that you have solved it in the master branch 😉

**Comment by billsimon** [comment]
Yes, I have also been working on testing this module with FreePBX 17. If you see any other issues please let me know or submit PR to master branch. Thanks!
