### ISSUE TITLE
Undefined variable $emailOffline on FreePBX 17

### ISSUE THREAD

**Issue by kd8grn** [simontelephonics/smsconnector#49]
Hi, 

I just migrated over to FreePBX 17. If I go into user manager, and try to add a new user it generates this error:

Whoops\Exception\ErrorException thrown with message "Undefined variable $emailOffline"

Stacktrace:
#7 Whoops\Exception\ErrorException in /var/www/html/admin/modules/smsconnector/Smsconnector.class.php:807
#6 Whoops\Run:handleError in /var/www/html/admin/modules/smsconnector/Smsconnector.class.php:807
#5 FreePBX\modules\Smsconnector:usermanShowPage in /var/www/html/admin/libraries/BMO/Hooks.class.php:320
#4 call_user_func_array in /var/www/html/admin/libraries/BMO/Hooks.class.php:320
#3 FreePBX\Hooks:executeCall in /var/www/html/admin/libraries/BMO/Hooks.class.php:355
#2 FreePBX\Hooks:processHooks in /var/www/html/admin/modules/userman/Userman.class.php:777
#1 FreePBX\modules\Userman:myShowPage in /var/www/html/admin/modules/userman/page.userman.php:2
#0 include in /var/www/html/admin/config.php:658

**Comment by billsimon** [comment]
Thanks for the bug report. I'll fix it in the next release, probably within a week.

**Comment by kd8grn** [comment]
Thanks, I appreciate all your work on this module.

**Comment by billsimon** [comment]
Fixed in version 16.0.17
