### ISSUE TITLE
Can send but can't receive SMS

### ISSUE THREAD

**Issue by fejorca** [simontelephonics/smsconnector#55]
Hello, I've downloaded and configured smsconnector on my server, I can send SMS but can't receive anything, here's my config

FreePBX 17.0.19.7 (Debian 12)
Provider: VoIP.ms
SMS Connector version: v16.0.17

freepbx.log (when sending an sms and try to receive)
`200818[2024-09-15 10:00:49] [freepbx.INFO]: voipms responds: HTTP 200, {"status":"success","sms":81944294} [] []
200819[2024-09-15 10:01:01] [freepbx.INFO]: Deprecated way to add Console commands for module api, adding console commands this way can have negative performance impacts. Please use module.xml. See: https://wiki.freepbx.org/display/FOP/Adding+fwconsole+commands [] []
200820[2024-09-15 10:01:01] [freepbx.INFO]: Deprecated way to add Console commands for module backup, adding console commands this way can have negative performance impacts. Please use module.xml. See: https://wiki.freepbx.org/display/FOP/Adding+fwconsole+commands [] []
200821[2024-09-15 10:01:01] [freepbx.INFO]: Deprecated way to add Console commands for module pbxmfa, adding console commands this way can have negative performance impacts. Please use module.xml. See: https://wiki.freepbx.org/display/FOP/Adding+fwconsole+commands [] []
200822[2024-09-15 10:01:01] [freepbx.INFO]: Deprecated way to add Console commands for module sangomartapi, adding console commands this way can have negative performance impacts. Please use module.xml. See: https://wiki.freepbx.org/display/FOP/Adding+fwconsole+commands [] []
200823[2024-09-15 10:01:01] [freepbx.INFO]: Deprecated way to add Console commands for module vmnotify, adding console commands this way can have negative performance impacts. Please use module.xml. See: https://wiki.freepbx.org/display/FOP/Adding+fwconsole+commands [] []
200824[2024-09-15 10:01:01] [freepbx.INFO]: Deprecated way to add Console commands for module voicemail, adding console commands this way can have negative performance impacts. Please use module.xml. See: https://wiki.freepbx.org/display/FOP/Adding+fwconsole+commands [] []
200825[2024-09-15 10:01:01] [freepbx.INFO]: Deprecated way to add Console commands for module api, adding console commands this way can have negative performance impacts. Please use module.xml. See: https://wiki.freepbx.org/display/FOP/Adding+fwconsole+commands [] []
200826[2024-09-15 10:01:01] [freepbx.INFO]: Deprecated way to add Console commands for module backup, adding console commands this way can have negative performance impacts. Please use module.xml. See: https://wiki.freepbx.org/display/FOP/Adding+fwconsole+commands [] []
200827[2024-09-15 10:01:01] [freepbx.INFO]: Deprecated way to add Console commands for module pbxmfa, adding console commands this way can have negative performance impacts. Please use module.xml. See: https://wiki.freepbx.org/display/FOP/Adding+fwconsole+commands [] []
200828[2024-09-15 10:01:01] [freepbx.INFO]: Deprecated way to add Console commands for module sangomartapi, adding console commands this way can have negative performance impacts. Please use module.xml. See: https://wiki.freepbx.org/display/FOP/Adding+fwconsole+commands [] []
200829[2024-09-15 10:01:01] [freepbx.INFO]: Deprecated way to add Console commands for module vmnotify, adding console commands this way can have negative performance impacts. Please use module.xml. See: https://wiki.freepbx.org/display/FOP/Adding+fwconsole+commands [] []
200830[2024-09-15 10:01:01] [freepbx.INFO]: Deprecated way to add Console commands for module voicemail, adding console commands this way can have negative performance impacts. Please use module.xml. See: https://wiki.freepbx.org/display/FOP/Adding+fwconsole+commands [] []
200831[2024-09-15 10:02:01] [freepbx.INFO]: Deprecated way to add Console commands for module api, adding console commands this way can have negative performance impacts. Please use module.xml. See: https://wiki.freepbx.org/display/FOP/Adding+fwconsole+commands [] []
200832[2024-09-15 10:02:01] [freepbx.INFO]: Deprecated way to add Console commands for module api, adding console commands this way can have negative performance impacts. Please use module.xml. See: https://wiki.freepbx.org/display/FOP/Adding+fwconsole+commands [] []
200833[2024-09-15 10:02:01] [freepbx.INFO]: Deprecated way to add Console commands for module backup, adding console commands this way can have negative performance impacts. Please use module.xml. See: https://wiki.freepbx.org/display/FOP/Adding+fwconsole+commands [] []
200834[2024-09-15 10:02:01] [freepbx.INFO]: Deprecated way to add Console commands for module backup, adding console commands this way can have negative performance impacts. Please use module.xml. See: https://wiki.freepbx.org/display/FOP/Adding+fwconsole+commands [] []
200835[2024-09-15 10:02:01] [freepbx.INFO]: Deprecated way to add Console commands for module pbxmfa, adding console commands this way can have negative performance impacts. Please use module.xml. See: https://wiki.freepbx.org/display/FOP/Adding+fwconsole+commands [] []
200836[2024-09-15 10:02:01] [freepbx.INFO]: Deprecated way to add Console commands for module pbxmfa, adding console commands this way can have negative performance impacts. Please use module.xml. See: https://wiki.freepbx.org/display/FOP/Adding+fwconsole+commands [] []
200837[2024-09-15 10:02:01] [freepbx.INFO]: Deprecated way to add Console commands for module sangomartapi, adding console commands this way can have negative performance impacts. Please use module.xml. See: https://wiki.freepbx.org/display/FOP/Adding+fwconsole+commands [] []
200838[2024-09-15 10:02:01] [freepbx.INFO]: Deprecated way to add Console commands for module sangomartapi, adding console commands this way can have negative performance impacts. Please use module.xml. See: https://wiki.freepbx.org/display/FOP/Adding+fwconsole+commands [] []
200839[2024-09-15 10:02:01] [freepbx.INFO]: Deprecated way to add Console commands for module vmnotify, adding console commands this way can have negative performance impacts. Please use module.xml. See: https://wiki.freepbx.org/display/FOP/Adding+fwconsole+commands [] []
200840[2024-09-15 10:02:01] [freepbx.INFO]: Deprecated way to add Console commands for module voicemail, adding console commands this way can have negative performance impacts. Please use module.xml. See: https://wiki.freepbx.org/display/FOP/Adding+fwconsole+commands [] []
200841[2024-09-15 10:02:01] [freepbx.INFO]: Deprecated way to add Console commands for module vmnotify, adding console commands this way can have negative performance impacts. Please use module.xml. See: https://wiki.freepbx.org/display/FOP/Adding+fwconsole+commands [] []
200842[2024-09-15 10:02:01] [freepbx.INFO]: Deprecated way to add Console commands for module voicemail, adding console commands this way can have negative performance impacts. Please use module.xml. See: https://wiki.freepbx.org/display/FOP/Adding+fwconsole+commands [] []
FreePBX®
`

The first line shows when I send an sms, on the other side I reply that message, on voip.ms site shows the message but my server doesn't get it, I've whitelisted voip.ms address and IP on FreePBX firewall, here's also a screenshot of UCP

![chrome_QJLGa80Gma](https://github.com/user-attachments/assets/3de47b4c-d0f4-49d5-bb74-c4d7f6bbf583)

I appreciate any help

**Comment by billsimon** [comment]
>  I've whitelisted voip.ms address and IP on FreePBX firewall

voip.ms does not publish the source IP of their webhooks. It is not the same as the SIP server. You should test by opening the firewall fully to allow inbound traffic to HTTPS (443) and see whether the webhooks are coming in from voip.ms.

**Comment by ItsSK** [comment]
> > I've whitelisted voip.ms address and IP on FreePBX firewall
> 
> voip.ms does not publish the source IP of their webhooks. It is not the same as the SIP server. You should test by opening the firewall fully to allow inbound traffic to HTTPS (443) and see whether the webhooks are coming in from voip.ms.

I also had the same issue, I was able to start receiving SMS/MMS after checking 'Internet' on FreePBX Web Management under services (see image)
![image](https://github.com/user-attachments/assets/6a4f8d86-7920-48f7-aa97-09d8325fa182)

I also noticed a pretty large delay between sending images and receiving them on the inbound side. Also sending images outbound is fast but doesn't include the caption (if it has a caption)

**Comment by RotatingWires** [comment]
I'm also having this problem, I can send but not receive messages through the UCP. I tried what @ItsSK mentioned, setting Web Management (Secure) to Internet, but that didn't work for me. I noticed that the webhook provider setting in the SMS connector module looked weird (two https://): 
![image](https://github.com/user-attachments/assets/0c779118-842e-483b-8baf-abb6f75622b2)
Not sure what to do next.
Thanks for any help

**Comment by RotatingWires** [comment]
@billsimon Is there anything I can do to remove the second `https://` from the webhook provider box? The field is not editable through the web UI.
Thanks

**Comment by billsimon** [comment]
Click the spinning gear here: 
![image](https://github.com/user-attachments/assets/b448cf6c-aad7-45f1-843f-94097d60c86b)

Change what is in the "FreePBX Web Address" field to your hostname (without a leading http/https).

**Comment by RotatingWires** [comment]
Thanks! Completely forgot to check that. Unfortunately, I still can't receive any messages. Retried what ItsSK showed after fixing the web address, no luck.

**Comment by billsimon** [comment]
It should not say `https://AMPWEBADDRESS`... the webhook should be `https://hostname.of.your.pbx.org/smsconn/...`

**Comment by RotatingWires** [comment]
Oh. My bad. I fixed that now. I also tried the other firewall stuff, no luck...
Thanks for your continued help. I'll keep trying, if you have any other ideas let me know

**Comment by billsimon** [comment]
Review `/var/log/asterisk/freepbx.log`, searching for `Webhook`. Any incoming webhooks that hit your server will be logged. If you don't see any, double check your firewall. You can also check apache web server logs in `/var/log/httpd`(SNG) or `/var/log/apache2` if you are running Debian. Look to see whether there are any incoming hits on the `smsconn` path.

**Comment by RotatingWires** [comment]
Hmm. Spent time checking everything you said. I didn't see any incoming webhooks to my server in the freepbx logfile, only outgoing ones. I even tried with the firewall off, still nothing in the log file. I will try my router's firewall now.. not sure if it'll help
