### ISSUE TITLE
SMS Webhook Question

### ISSUE THREAD

**Issue by RotatingWires** [simontelephonics/smsconnector#66]
I’ve had great success with this module, I just want to ask about FreePBX’s SMS webhook module. I want to use this module for SMS notifications/logs when messages are sent or received. I put in a discord webhook to test it out and sent a message but no webhook was sent. I tried some things to fix it, like allowing discord.com through the firewall, but still didn’t receive anything. Does the SMS webhook module only work for the native SMS functionality, and not with this module? I’m not sure how it works.

Thanks

**Comment by billsimon** [comment]
SMS Webhook works with the SMS Connector.

Try getting a webhook endpoint from http://webhook.site and plug that in to SMS Webhook.

![image](https://github.com/user-attachments/assets/07f25b3b-d820-46cc-b863-887ca6700f81)

**Comment by RotatingWires** [comment]
I’ll have to try that when I have the SMSConnector module working again. I had it working before, but I recently updated to FreePBX 17 and when I run the commands in the read me to install the module it gives me an error saying that the tar file is not in the correct format for some reason

**Comment by billsimon** [comment]
`fwconsole ma downloadinstall https://github.com/simontelephonics/smsconnector/releases/download/v16.0.17.2/smsconnector-16.0.17.2.tar.gz`
`fwconsole r`

I just ran this successfully on a FreePBX17 system. Let me know if you get different results.

**Comment by RotatingWires** [comment]
![IMG_3458](https://github.com/user-attachments/assets/e9a4283b-5789-41b2-997d-3b7a1df72652)

**Comment by RotatingWires** [comment]
I’m running FreePBX in a VirtualBox VM with the host being Xubuntu. I’ve made sure to turn on bidirectional clipboards, but the VM won’t paste what I have copied. I thought I made sure there were no typos but I can try again

Thanks

**Comment by RotatingWires** [comment]
@billsimon I tested it. Yes, the webhook does reach that site.
