### ISSUE TITLE
Messages not received on recipient device when SIP TLS enabled

### ISSUE THREAD

**Issue by RotatingWires** [simontelephonics/smsconnector#67]
I recently tried to enable SIP TLS on FreePBX. I went to Settings > Asterisk SIP Settings > SIP Settings > Set the LE cert > Set TLS to All. When I had no cert selected and the TLS setting to No, messages would send and receive fine. When I selected the cert and set TLS to Yes, I could messages would be shown as sent but I would never actually receive a message. I first got an error for AGI, but that went away on a reboot. Then I tried sending a message again, and the logfiles make it seem like the message was sent. I never received the message though. Is there some other setting I need to change now that I have TLS enabled for SMS to work?
![image](https://github.com/user-attachments/assets/25f7401e-e1b7-4fb4-914d-71d412cbdd57)
![image](https://github.com/user-attachments/assets/9101a79d-8f67-4ef8-b053-c71b6efdadbd)

Thanks

**Comment by billsimon** [comment]
I don't know of any issues with SIP TLS. I tested it in my lab. Check /var/log/asterisk/freepbx.log for information from the SMS Connector.

**Comment by RotatingWires** [comment]
https://community.freepbx.org/t/agi-127-0-0-1-connection-refused/95641/

That unfortunately did not work for me

**Comment by RotatingWires** [comment]
It’s running. I restarted it to try again but it didn’t work after a restart either.

**Comment by billsimon** [comment]
OK, well it's out of scope for this module. The module uses agi which _should_ be working and is expected to work as a normal part of FreePBX/Asterisk. Please post in the community forum for more general help on getting fastagi working.

**Comment by billsimon** [comment]
It's failing on this...

```
						$this->addLog('WebHook', 'Post', $hook['webhookUrl'], ['status' => false, 'message' => _('Failed to send data to the configured web hook. Due to' . (string) $ret)], $code);
```

Can you try disabling your SMS Webhook and try again?
